# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foster_home.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='foster_home.proto',
  package='Obn.Service.FosterHome',
  syntax='proto3',
  serialized_options=b'\352\002\030Obn::Service::FosterHome',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x66oster_home.proto\x12\x16Obn.Service.FosterHome\x1a\x19google/protobuf/any.proto\"\x1f\n\x11\x46osterHomeRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"O\n\x17\x46osterHomeSearchRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\x12$\n\x06values\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"\x8c\x01\n\nFosterHome\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\x12\n\npostalCode\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x07 \x01(\t\x12\r\n\x05\x65Mail\x18\x08 \x01(\t\"K\n\x16\x46osterHomeSearchResult\x12\x31\n\x05homes\x18\x01 \x03(\x0b\x32\".Obn.Service.FosterHome.FosterHome\")\n\x16\x46osterHomeDeleteResult\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\x82\x03\n\x11\x46osterHomeService\x12T\n\x03get\x12).Obn.Service.FosterHome.FosterHomeRequest\x1a\".Obn.Service.FosterHome.FosterHome\x12i\n\x06search\x12/.Obn.Service.FosterHome.FosterHomeSearchRequest\x1a..Obn.Service.FosterHome.FosterHomeSearchResult\x12N\n\x04save\x12\".Obn.Service.FosterHome.FosterHome\x1a\".Obn.Service.FosterHome.FosterHome\x12\\\n\x06\x64\x65lete\x12\".Obn.Service.FosterHome.FosterHome\x1a..Obn.Service.FosterHome.FosterHomeDeleteResultB\x1b\xea\x02\x18Obn::Service::FosterHomeb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_FOSTERHOMEREQUEST = _descriptor.Descriptor(
  name='FosterHomeRequest',
  full_name='Obn.Service.FosterHome.FosterHomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Obn.Service.FosterHome.FosterHomeRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=103,
)


_FOSTERHOMESEARCHREQUEST = _descriptor.Descriptor(
  name='FosterHomeSearchRequest',
  full_name='Obn.Service.FosterHome.FosterHomeSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='Obn.Service.FosterHome.FosterHomeSearchRequest.filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='Obn.Service.FosterHome.FosterHomeSearchRequest.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=184,
)


_FOSTERHOME = _descriptor.Descriptor(
  name='FosterHome',
  full_name='Obn.Service.FosterHome.FosterHome',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Obn.Service.FosterHome.FosterHome.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Obn.Service.FosterHome.FosterHome.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='Obn.Service.FosterHome.FosterHome.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city', full_name='Obn.Service.FosterHome.FosterHome.city', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='postalCode', full_name='Obn.Service.FosterHome.FosterHome.postalCode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='Obn.Service.FosterHome.FosterHome.state', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phoneNumber', full_name='Obn.Service.FosterHome.FosterHome.phoneNumber', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eMail', full_name='Obn.Service.FosterHome.FosterHome.eMail', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=327,
)


_FOSTERHOMESEARCHRESULT = _descriptor.Descriptor(
  name='FosterHomeSearchResult',
  full_name='Obn.Service.FosterHome.FosterHomeSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='homes', full_name='Obn.Service.FosterHome.FosterHomeSearchResult.homes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=404,
)


_FOSTERHOMEDELETERESULT = _descriptor.Descriptor(
  name='FosterHomeDeleteResult',
  full_name='Obn.Service.FosterHome.FosterHomeDeleteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deleted', full_name='Obn.Service.FosterHome.FosterHomeDeleteResult.deleted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=447,
)

_FOSTERHOMESEARCHREQUEST.fields_by_name['values'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_FOSTERHOMESEARCHRESULT.fields_by_name['homes'].message_type = _FOSTERHOME
DESCRIPTOR.message_types_by_name['FosterHomeRequest'] = _FOSTERHOMEREQUEST
DESCRIPTOR.message_types_by_name['FosterHomeSearchRequest'] = _FOSTERHOMESEARCHREQUEST
DESCRIPTOR.message_types_by_name['FosterHome'] = _FOSTERHOME
DESCRIPTOR.message_types_by_name['FosterHomeSearchResult'] = _FOSTERHOMESEARCHRESULT
DESCRIPTOR.message_types_by_name['FosterHomeDeleteResult'] = _FOSTERHOMEDELETERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FosterHomeRequest = _reflection.GeneratedProtocolMessageType('FosterHomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOSTERHOMEREQUEST,
  '__module__' : 'foster_home_pb2'
  # @@protoc_insertion_point(class_scope:Obn.Service.FosterHome.FosterHomeRequest)
  })
_sym_db.RegisterMessage(FosterHomeRequest)

FosterHomeSearchRequest = _reflection.GeneratedProtocolMessageType('FosterHomeSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOSTERHOMESEARCHREQUEST,
  '__module__' : 'foster_home_pb2'
  # @@protoc_insertion_point(class_scope:Obn.Service.FosterHome.FosterHomeSearchRequest)
  })
_sym_db.RegisterMessage(FosterHomeSearchRequest)

FosterHome = _reflection.GeneratedProtocolMessageType('FosterHome', (_message.Message,), {
  'DESCRIPTOR' : _FOSTERHOME,
  '__module__' : 'foster_home_pb2'
  # @@protoc_insertion_point(class_scope:Obn.Service.FosterHome.FosterHome)
  })
_sym_db.RegisterMessage(FosterHome)

FosterHomeSearchResult = _reflection.GeneratedProtocolMessageType('FosterHomeSearchResult', (_message.Message,), {
  'DESCRIPTOR' : _FOSTERHOMESEARCHRESULT,
  '__module__' : 'foster_home_pb2'
  # @@protoc_insertion_point(class_scope:Obn.Service.FosterHome.FosterHomeSearchResult)
  })
_sym_db.RegisterMessage(FosterHomeSearchResult)

FosterHomeDeleteResult = _reflection.GeneratedProtocolMessageType('FosterHomeDeleteResult', (_message.Message,), {
  'DESCRIPTOR' : _FOSTERHOMEDELETERESULT,
  '__module__' : 'foster_home_pb2'
  # @@protoc_insertion_point(class_scope:Obn.Service.FosterHome.FosterHomeDeleteResult)
  })
_sym_db.RegisterMessage(FosterHomeDeleteResult)


DESCRIPTOR._options = None

_FOSTERHOMESERVICE = _descriptor.ServiceDescriptor(
  name='FosterHomeService',
  full_name='Obn.Service.FosterHome.FosterHomeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=450,
  serialized_end=836,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='Obn.Service.FosterHome.FosterHomeService.get',
    index=0,
    containing_service=None,
    input_type=_FOSTERHOMEREQUEST,
    output_type=_FOSTERHOME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='search',
    full_name='Obn.Service.FosterHome.FosterHomeService.search',
    index=1,
    containing_service=None,
    input_type=_FOSTERHOMESEARCHREQUEST,
    output_type=_FOSTERHOMESEARCHRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='Obn.Service.FosterHome.FosterHomeService.save',
    index=2,
    containing_service=None,
    input_type=_FOSTERHOME,
    output_type=_FOSTERHOME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='Obn.Service.FosterHome.FosterHomeService.delete',
    index=3,
    containing_service=None,
    input_type=_FOSTERHOME,
    output_type=_FOSTERHOMEDELETERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOSTERHOMESERVICE)

DESCRIPTOR.services_by_name['FosterHomeService'] = _FOSTERHOMESERVICE

# @@protoc_insertion_point(module_scope)
