# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import foster_home_pb2 as foster__home__pb2


class FosterHomeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/Obn.Service.FosterHome.FosterHomeService/get',
                request_serializer=foster__home__pb2.FosterHomeRequest.SerializeToString,
                response_deserializer=foster__home__pb2.FosterHome.FromString,
                )
        self.search = channel.unary_unary(
                '/Obn.Service.FosterHome.FosterHomeService/search',
                request_serializer=foster__home__pb2.FosterHomeSearchRequest.SerializeToString,
                response_deserializer=foster__home__pb2.FosterHomeSearchResult.FromString,
                )
        self.save = channel.unary_unary(
                '/Obn.Service.FosterHome.FosterHomeService/save',
                request_serializer=foster__home__pb2.FosterHome.SerializeToString,
                response_deserializer=foster__home__pb2.FosterHome.FromString,
                )
        self.delete = channel.unary_unary(
                '/Obn.Service.FosterHome.FosterHomeService/delete',
                request_serializer=foster__home__pb2.FosterHome.SerializeToString,
                response_deserializer=foster__home__pb2.FosterHomeDeleteResult.FromString,
                )


class FosterHomeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FosterHomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=foster__home__pb2.FosterHomeRequest.FromString,
                    response_serializer=foster__home__pb2.FosterHome.SerializeToString,
            ),
            'search': grpc.unary_unary_rpc_method_handler(
                    servicer.search,
                    request_deserializer=foster__home__pb2.FosterHomeSearchRequest.FromString,
                    response_serializer=foster__home__pb2.FosterHomeSearchResult.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=foster__home__pb2.FosterHome.FromString,
                    response_serializer=foster__home__pb2.FosterHome.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=foster__home__pb2.FosterHome.FromString,
                    response_serializer=foster__home__pb2.FosterHomeDeleteResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Obn.Service.FosterHome.FosterHomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FosterHomeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Obn.Service.FosterHome.FosterHomeService/get',
            foster__home__pb2.FosterHomeRequest.SerializeToString,
            foster__home__pb2.FosterHome.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Obn.Service.FosterHome.FosterHomeService/search',
            foster__home__pb2.FosterHomeSearchRequest.SerializeToString,
            foster__home__pb2.FosterHomeSearchResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Obn.Service.FosterHome.FosterHomeService/save',
            foster__home__pb2.FosterHome.SerializeToString,
            foster__home__pb2.FosterHome.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Obn.Service.FosterHome.FosterHomeService/delete',
            foster__home__pb2.FosterHome.SerializeToString,
            foster__home__pb2.FosterHomeDeleteResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
